### ISSUE TITLE
Ubuntu環境において、ROS対応バイナリのビルドが失敗する

### ISSUE THREAD

**Issue by TE-TakuyaSugitani** [shiguredo/momo#110]
**バグを説明してください**

Ubuntu + docker環境において、ROS対応バイナリのビルドがエラーで失敗してしまいます

**再現する**

ビルド環境は以下の通りです
```
Ubuntu 18.04.3 LTS
Docker version 19.03.3., build a872fc2f86
```
※バイナリのビルド環境はUbuntu 18.04ですが、実行は別環境で行う予定でした

USE_ROS.md を参考に、以下のコマンドを実行しました
```
make ubuntu-16.04_x86_64_ros.clean
make ubuntu-16.04_x86_64_ros
```

**予想される行動**

ビルドが完了し、momoのバイナリが作成される

**自前バイナリ/提供バイナリ**

以下のコミットハッシュ時点のコードをビルドしています
```
b5c3fa7e738ca7576ee4c794c6500ccbeb8c029c
```

**ビルドログ**

ビルドログ中のエラーと思われる箇所は以下の通りです
[momo_ros_x86_error.txt](https://github.com/shiguredo/momo/files/3817939/momo_ros_x86_error.txt)

**Comment by voluntas** [comment]
@TE-TakuyaSugitani 報告ありがとうございます。ビルドが通らないことこちらでも確認できました。調査進めていきます。

**Comment by voluntas** [comment]
@TE-TakuyaSugitani f628611035f978ed478ab70c49a78dddfd971d6c の最新の develop にて修正しましたので、ご確認いただけますか？

**Comment by TE-TakuyaSugitani** [comment]
@voluntas 
無事ビルドが通ることを確認しました。ご対応ありがとうございます！
