### ISSUE TITLE
ジェットソンナノラスピカムが検出されない

### ISSUE THREAD

**Issue by dftpnd** [shiguredo/momo#136]
jetson nano raspi cam not detected
<img width="439" alt="Screenshot 2020-03-06 at 17 28 56" src="https://user-images.githubusercontent.com/3207851/76092150-f7e3ec80-5fcf-11ea-8125-9f145137ffcd.png">
<img width="1693" alt="Screenshot 2020-03-06 at 17 29 20" src="https://user-images.githubusercontent.com/3207851/76092178-04684500-5fd0-11ea-8bb6-3655528fe961.png">

**Comment by tnoho** [comment]
Sorry I have not tested with Raspberry Pi Camera. Thank you for share logs with us.
I seem the camera supported only one video format "RG10". But our program is not support it.
If you want to try to use that camera. You have to add some transform programs inside capture process.
RG10 means 10bit sRGB. It conversion is not so difficult. If you can please try to support it.

The color format conversion has written in following file.
https://github.com/shiguredo/momo/blob/develop/src/rtc/scalable_track_source.cpp#L78

But use USB camera is easiest way for you. Momo supports common USB camera formats.
Your car seems so cool! I'm looking forward to add POV function in this car. Thanks.

**Comment by tnoho** [comment]
Sorry we don't support CSI camera now and we don't have any plans for support it. We are only supports USB camera. It's specification. It's not bug then I close this issue.

**Comment by dftpnd** [comment]
Спасибо) желаю удави вашему проекту!
