### ISSUE TITLE
metadata 部分を json::parse してから格納するようにする

### ISSUE THREAD

**Issue by voluntas** [shiguredo/momo#15]
https://github.com/shiguredo/momo/blob/master/src/sora/sora_connection.cpp#L139

例外処理とかどうするかは考える。

**Comment by voluntas** [comment]
@melpon これって対応できますか？

**Comment by melpon** [comment]
単に parse すれば良いだけですか？

**Comment by voluntas** [comment]
今は文字列のままいれこむのだけれど、json 形式で入れ込みたいので、json 形式で parse できるかどうかのエラーハンドリングもお願いしたいです。

parse -> JSON 形式としてパースできない -> エラーで momo 実行されないという感じです。

**Comment by voluntas** [comment]
確認してマージしました！
