### ISSUE TITLE
ubuntu-20.04_x86_64 での NVENC の動作テスト

### ISSUE THREAD

**Issue by voluntas** [shiguredo/momo#154]
https://github.com/shiguredo/momo/pull/152 からの移植。

[cuda-toolkit 公式](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html)では Ubuntu 20.04 はサポートされていないので、ビルドはできても実機での動作確認は行っていないので、確認が必要。

**Comment by hakobera** [comment]
CUDA 11.0 から Ubuntu 20.04 に正式対応したようです。CUDA 11.0 に上げるタイミングで確認すれば良いのではないかと思います。

**Comment by torikizi** [comment]
ubuntu-20.04_x86_64/ CUDA 11.0 を使って動作確認できました。既知の問題以外は一通り問題なく動いていました。

**Comment by voluntas** [comment]
動作確認済みなので閉じます。
