### ISSUE TITLE
cannot find lnvbuf_fdmap

### ISSUE THREAD

**Issue by honggesmile** [shiguredo/momo#177]
hardware: jetson tx2
system :ubuntu18.04
jetpack: 4.2

first,thanks for your work. When compiling the project, the following error occurred:
`/usr/bin/ld: connot found -lnvbuf_fdmap`, i canot find libnvbuf_fdmap.so on my system, so what should i do ?
thanks a lot.

**Comment by voluntas** [comment]
@honggesmile Discord を経由しない Issue は受け付けていません。
