### ISSUE TITLE
sora-js-sdkにて、connection確立時の"addstream"callbackが呼ばれない

### ISSUE THREAD

**Issue by messi49** [shiguredo/momo#18]
下記環境にて、momoとsoraの連携に少し問題が有りました。

## 環境
[配信側]
端末: x86
カメラ: BUFFALO BSWHD06M
OS: Ubuntu 18.04 64bit
Momo: momo-18.10.0-rc0_ubuntu_x86_64

[受信側]
端末: x86
ブラウザ: chrome69
OS: Ubuntu 16.04 64bit
sora-js-sdk: 1.9.2

実行コマンド
```
$ ./momo --no-audio --video-codec H264 --video-bitrate 2000 sora --auto wss://{sora_url}/signaling Sora
```

上記実行コマンド後、JS側でconnectionが確立されるが、addstreamが呼ばれない。
connection確立後、addstream内ではなくconnect後にstreamをremoteVideosに紐付ければ一応は映像が表示される。

```
document.querySelector('#start-subscriber').addEventListener('click', function() {
  subscriber.connect()
    .catch(e => {
      console.error(e);
    });
  subscriber.on('addstream', function(event) {
    var remoteVideos = document.querySelector('#remote-videos');
    var remoteVideo = document.createElement('video');
    remoteVideo.id = 'publisher-remotevideo-' + event.stream.id;
    remoteVideo.style.border = '1px solid red';
    remoteVideo.autoplay = true;
    remoteVideo.width = '320';
    remoteVideo.height = '240';
    remoteVideo.srcObject = event.stream;
    remoteVideos.appendChild(remoteVideo);
  });
  subscriber.on('removestream', function(event) {
    var remoteVideo = document.querySelector('#publisher-remotevideo-' + event.stream.id);
    document.querySelector('#remote-videos').removeChild(remoteVideo);
  });
});
```
※上記、https://github.com/shiguredo/sora-js-sdk/blob/develop/example/multistream_down.html から抜粋

**Comment by Hexa** [comment]
@messi49 singleStream の場合に subscriber.on('addstream', callback) で登録した callback が実行されない sora-js-sdk 側の不具合でした。
現在、sora-js-sdk を修正しておりますので、今しばらくお待ちください。

**Comment by Hexa** [comment]
@messi49 お待たせいたしました。
Single Stream の subscriber で on('addstream', callback) で登録した callback が実行されるように修正された sora-js-sdk 1.9.3 です。

https://github.com/shiguredo/sora-js-sdk/tree/1.9.3

こちらでご確認いただけますでしょうか。
よろしくお願いいたします。

**Comment by messi49** [comment]
@Hexa addstreamのcallbackが実行されることを確認致しました。ご対応ありがとうございます。
