### ISSUE TITLE
次の問題が発生しました  /usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(entropymv.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000

### ISSUE THREAD

**Issue by honggesmile** [shiguredo/momo#180]
まずはお疲れ様でした。このプロジェクトをjetsonxavier nxでコンパイルしたときに、コンパイルしたlibwebrtc.aファイルをCMakeLists.txt、set（CMAKE_INCLUDE_PATH "webrtc / include"）に直接追加しました。
set（CMAKE_LIBRARY_PATH "webrtc / lib"）、コンパイル時に次の警告が表示されました：
`[ 97%] Building CXX object CMakeFiles/momo.dir/usr/src/jetson_multimedia_api/samples/common/classes/NvVideoDecoder.cpp.o
1 warning generated.
[100%] Linking CXX executable momo
/usr/bin/aarch64-linux-gnu-ld: warning: CMakeFiles/momo.dir/usr/src/jetson_multimedia_api/samples/common/classes/NvLogging.cpp.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(entropymv.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(modecont.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(err_data.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(media_constants.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(constants.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(p2p_constants.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(lpc_shape_swb12_tables.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(pulseaudiosymboltable_linux.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(tables_other.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(tables_pitch_lag.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(tables_NLSF_CB_NB_MB.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(tables_NLSF_CB_WB.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(resampler_rom.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(tables_pulses_per_block.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(tables_LTP.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(tables_gain.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(blockd.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(vp9_scan.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(vp9_common_data.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(txb_common.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(scan.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(odintrin.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(spl_init.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(fec_private_tables_random.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(constants.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(lpc_shape_swb16_tables.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(lpc_tables.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(lpc_gain_swb_tables.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(pitch_gain_tables.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(pitch_lag_tables.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(alsasymboltable_linux.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(table_LSF_cos.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(mlp_data.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(vp9_filter.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(fec_private_tables_bursty.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(spectrum_ar_model_tables.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(pitch_est_tables.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/aarch64-linux-gnu-ld: warning: ../webrtc/lib/libwebrtc.a(rnn_vad_weights.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
[100%] Built target momo
`

momoを実行すると、エラーは次のようになります：
`nvidia@nvidia:~/chris/jetson_momo/build$ ./momo --resolution=HD --use-native test
Opening in BLOCKING MODE 
Opening in BLOCKING MODE 
Segmentation fault (core dumped)
`

これはlibwebrtcの問題ですか、返信をお待ちしております。ありがとうございます。

**Comment by voluntas** [comment]
discord で相談がないため閉じます。
