### ISSUE TITLE
Jetson nano build error

### ISSUE THREAD

**Issue by rasheeddo** [shiguredo/momo#182]
すみません, 最新のJetson nano JetPack 4.4, 以下の手順に従いましたが、ビルドエラーが発生しました
```
git clone https://github.com/shiguredo/momo.git
cd momo/build/
sudo ./build.sh ubuntu-18.04_armv8_jetson_nano
```
この種のエラーが表示されます

![momo error1](https://user-images.githubusercontent.com/33745402/96582678-967e4d00-1316-11eb-910f-f17bde3450e9.png)
![momo error2](https://user-images.githubusercontent.com/33745402/96582682-98481080-1316-11eb-97ef-39381807c7e1.png)

`./build.sh --clean ubuntu-18.04_armv8_jetson_nano && ./build.sh ubuntu-18.04_armv8_jetson_nano `
これをしてもまだ同じです

修正する方法を教えて よろしくおねがいいたします

**Comment by voluntas** [comment]
Discord での相談がないため、閉じます。
