### ISSUE TITLE
The problem of using makefile to compile the project

### ISSUE THREAD

**Issue by loveCatCoder** [shiguredo/momo#184]
I need to use the makefile I wrote to compile this project. Everything is going well, but there are some problems when linking. The output is below.I did not link openssl in the program, because webrtc uses boringssl, how should I solve this problem. Thank you。

`websocket.o: In function `Websocket::Connect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (boost::system::error_code)>)':
websocket.cpp:(.text+0xf3d): undefined reference to `SSL_ctrl'
websocket.o: In function `boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)':
websocket.cpp:(.text._ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE[_ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE]+0x11c): undefined reference to `SSL_CTX_ctrl'
websocket.cpp:(.text._ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE[_ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE]+0x139): undefined reference to `SSL_CTX_ctrl'
websocket.cpp:(.text._ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE[_ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE]+0x195): undefined reference to `SSL_CTX_ctrl'
websocket.cpp:(.text._ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE[_ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE]+0x1b2): undefined reference to `SSL_CTX_ctrl'
websocket.cpp:(.text._ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE[_ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE]+0x21a): undefined reference to `SSL_CTX_ctrl'
websocket.o:websocket.cpp:(.text._ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE[_ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE]+0x237): more undefined references to `SSL_CTX_ctrl' follow
websocket.o: In function `boost::asio::ssl::detail::engine::engine(ssl_ctx_st*)':
websocket.cpp:(.text._ZN5boost4asio3ssl6detail6engineC2EP10ssl_ctx_st[_ZN5boost4asio3ssl6detail6engineC2EP10ssl_ctx_st]+0x77): undefined reference to `SSL_ctrl'
websocket.cpp:(.text._ZN5boost4asio3ssl6detail6engineC2EP10ssl_ctx_st[_ZN5boost4asio3ssl6detail6engineC2EP10ssl_ctx_st]+0x95): undefined reference to `SSL_ctrl'
websocket.cpp:(.text._ZN5boost4asio3ssl6detail6engineC2EP10ssl_ctx_st[_ZN5boost4asio3ssl6detail6engineC2EP10ssl_ctx_st]+0xb3): undefined reference to `SSL_ctrl'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:67: recipe for target 'momo' failed
make[1]: *** [momo] Error 1
make[1]: Leaving directory '/home/zn/Desktop/momo/src'
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by voluntas** [comment]
Discord での相談なしのため閉じます。
