### ISSUE TITLE
stderr:===== NVMEDIA: NVENC =====

### ISSUE THREAD

**Issue by cronos-dcrop** [shiguredo/momo#197]
is this normal?

momo.on.stderr:NvMMLiteOpen : Block : BlockType = 4 

momo.on.stderr:===== NVMEDIA: NVENC =====
NvMMLiteBlockCreate : Block : BlockType = 4 

momo.on.stdout:libv4l2_nvvidconv (0):(802) (INFO) : Allocating (1) OUTPUT PLANE BUFFERS Layout=0
libv4l2_nvvidconv (0):(818) (INFO) : Allocating (10) CAPTURE PLANE BUFFERS Layout=0
Opening in BLOCKING MODE 
875967048
842091865

momo.on.stderr:H264: Profile = 100, Level = 51 

i am experiencing some blank screens when streaming for long time with momo.
sometimes i got a white screen on the browser then it take about 2 to 5 minutes to show the cammera image again...
i wonder if the above error is ralated with the problem.

ps: i am using Jetson nano + momo 2020.1 + ayame sdk (should i upgrade??)

thank you.

**Comment by voluntas** [comment]
Discord での相談がないため閉じます。

詳細は、以下をお読み下さい。
https://github.com/shiguredo/oss
