### ISSUE TITLE
Jpeg library error

### ISSUE THREAD

**Issue by robi772** [shiguredo/momo#228]
**不和IDを教えてください**

Robi＃6287

**バグを説明してください**

jetpack4.5と4.6の両方を備えたjetsonnanoでは、ストリームを開始しようとするとこのエラーが発生します
間違ったJPEGライブラリバージョン：ライブラリは62、発信者は80を期待しています

**複製**

./momo --hw-mjpeg-decoder true --framerate 30 --log-level 2 --no-audio-device --video-device / dev / video1 sora \
    wss：//sora-labo.shiguredo.jp/signaling robi772 @ sora-devtools \
    --video true --audio 0 \
    --video-codec-type VP8 --video-bit-rate 15000 \
    --auto --role sendonly --multistream true \
    -メタデータ '{"signaling_key"： ""}'

** 予想される行動 **

ソラへのストリームを開始する必要があります

**実際の操作**

モモを閉じる

**カメラ/マイク**

Logitech C920 /音声なし

バス002デバイス002：ID 0bda：0411 Realtek Semiconductor Corp.
バス002デバイス001：ID 1d6b：0003 Linux Foundation3.0ルートハブ
バス001デバイス003：ID 8087：0a2b Intel Corp.
バス001デバイス006：ID 2341：804d Arduino SA
バス001デバイス010：ID 046d：082d Logitech、Inc。HD Pro Webcam C920
バス001デバイス008：ID 10c4：ea60 Cygnal Integrated Products、Inc。CP210xUARTブリッジ/ myAVRmySmartUSBライ

ト
バス001デバイス007：ID 0a05：7211不明なメーカーハブ
バス001デバイス005：ID 0a05：7211不明なメーカーハブ
バス001デバイス009：ID 2341：804d Arduino SA
バス001デバイス002：ID 0bda：5411 Realtek Semiconductor Corp.
バス001デバイス001：ID 1d6b：0002 Linux Foundation2.0ルートハブ

**独自のバイナリ/提供されたバイナリ**

jetpack4.6にはクリーンインストールがあります

**-ログレベル1の出力ログ**

** 追加情報 **

この問題に関する詳細情報をここに追加してください。 

[momo-log1.txt](https://github.com/shiguredo/momo/files/7574354/momo-log1.txt)

**Comment by voluntas** [comment]
discord での相談がないため閉じます。
