### ISSUE TITLE
Momo 同士で繋いだ際 --serial が利用できない

### ISSUE THREAD

**Issue by voluntas** [shiguredo/momo#237]
## 問題

- Momo 同士での --serial を想定していない実装となっているため非対応
- Momo 側の Offer/Answer 側からは createDataChannel を行っていない

## 修正仕様

Momo 側から Offer を送った際、--serial を引数として指定した場合は createDataChannel してから送る。

## 優先度

低い。

**Comment by torikizi** [comment]
こちら以下の PR で対応済みのためクローズします。
https://github.com/shiguredo/momo/pull/243
