### ISSUE TITLE
Momo 2024.1.0 について

### ISSUE THREAD

**Issue by voluntas** [shiguredo/momo#331]
**予定は未定です**

- 2024 年 9 月末頃にリリース予定です
- Raspberry Pi OS 32 bit 対応をドロップします
- Ubuntu 20.04 対応をドロップします
- Ubuntu 24.04 対応します
- Ubuntu 20.04 NVIDIA Jetson JetPack 5 系対応をドロップします
- Ubuntu 22.04 NVIDIA Jetson JetPack 6 系対応します
- Intel VPL 対応します
  - H.265 対応します
  - AV1 対応予定です
- macOS Video Toolbox
  - H.265 対応します
- NVIDIA Video Codec SDK
  - H.265 対応します
- OpenH264 対応予定です
- `--video-device` の指定がファイル名ではなくデバイス名に変わります

ドロップした対応は優先実装でお受けします。

**Comment by miosakuma** [comment]
Momo 2024.1.0 がリリースされました。
こちらのイシューはクローズします。
