### ISSUE TITLE
P2P モードで Web サーバとして立ち上がったとき、カレントディレクトリ晒さないようオプション化する

### ISSUE THREAD

**Issue by voluntas** [shiguredo/momo#4]
p2p 向けの機能なので ./momo p2p --document-root オプションをお願いします。

**Comment by melpon** [comment]
- `--document-root` オプションを追加する。省略時は `./html` になるようにする
- ディレクトリをアクセスした時に一覧が見えないようにする

の対応をする。けどよく考えたら Boost.Beast に移行するならそっちを先にやった方が二度手間にならないので #7 を先に試してみる。

**Comment by voluntas** [comment]
こちら了解。 #7 優先で問題ないです。一旦 18.12.0 のほうにマイルストーンずらしておきます。

**Comment by melpon** [comment]
`--document-root` オプションは追加してない（常にカレントディレクトリがドキュメントルートになる）ですけど大丈夫ですか？

**Comment by voluntas** [comment]
たしかに --document-root はほしい気がしますね。reopen してタスクとして残しておきます。

**Comment by Hexa** [comment]
--document-root  の動作も確認できたため閉じます。
