### ISSUE TITLE
カメラノードを起動していない場合に、ROS 版 の momo を Ctrl+C で停止できない

### ISSUE THREAD

**Issue by Hexa** [shiguredo/momo#40]
rosrun usb_cam usb_cam_node ... でカメラノードを起動せずに、ROS 版 の momo のみを立ち上げて、momo を Ctrl+C で停止させようとすると momo が停止しなくなります。

Ctrl+C の前にカメラノードを起動させてしまえば、その後は momo は Ctrl+C でも停止しますが、カメラノードの起動前に、Ctrl+C を実行してしまうと後からカメラノードを起動しても momo を Ctrl+C で停止できなくなります。

これは p2p モード、sora モードのどちらの場合でも再現することを確認しています。

```
$ ./momo  _use_p2p:=true _compressed:=true image:=/usb_cam0/image_raw/compressed _log_level:=3
^C
```

**Comment by tnoho** [comment]
VideoCaptureの初期化を行うためROSからのフレームを2枚待つ実装があり、そこでループを抜けられなくなっていたために発生していました。
c03ae25 で修正済みです。

**Comment by Hexa** [comment]
ありがとうございます
Ctrl+C で停止できることを確認しました
