### ISSUE TITLE
macOSでraspbian-stretch_armv7向けビルドのエラー 

### ISSUE THREAD

**Issue by mganeko** [shiguredo/momo#62]
macOS High Sierra 10.13.6 + docker (Engine 18.09.2) で、raspbian-stretch_armv7 をターゲットにビルドしたところ、途中でエラーが出て停止しましたので、お伝えします。
停止する直前のコンソール出力を、こちらに掲載しておきます。
https://gist.github.com/mganeko/c249cfc90f0f777f2be525896379c042

同じ環境で、ubuntu-18.04_x86_64 をターゲットにしたビルドは成功しました。

**Comment by voluntas** [comment]
@mganeko こちらおそらくファイルシステムが大文字と小文字の認識をしない環境でビルドしたことが問題のようです。HEAD にて修正済みですので、確認をお願い致します。

**Comment by mganeko** [comment]
対応ありがとうございます。ビルドできました！
