### ISSUE TITLE
civetweb から beast の置き換えを検討する

### ISSUE THREAD

**Issue by voluntas** [shiguredo/momo#7]
- [boostorg/beast: HTTP and WebSocket built on Boost\.Asio in C\+\+11](https://github.com/boostorg/beast)
- 変更箇所
  - HTTP API
  - WebSocket

これにより civietweb と websocketpp を beast で置き換えられるはず。

**Comment by Hexa** [comment]
置き換え後の動作の確認も取れたため閉じます
