### ISSUE TITLE
Raspberry Pi 3B+ の raspbian 9.9 上で killed by SIGABRT

### ISSUE THREAD

**Issue by anatawa12** [shiguredo/momo#74]
raspberry pi 3B+(リビジョン番号a020d3)でmomo-19.02.0_raspbian-stretch_armv7を実行するとAbortedと表示されて落ちます。

実行時のコマンドはこちらです。
`./momo --no-audio --video-codec VP8 --video-bitrate 800 --port 8080 p2p`

straceの出力です。
[trace.txt](https://github.com/shiguredo/momo/files/3265373/trace.txt)

**Comment by voluntas** [comment]
@anatawa12 OS のバージョン、利用しているカメラの種類などの情報もいただけますでしょうか？

**Comment by anatawa12** [comment]
カメラはロジクール製UVCカメラです。
OSは
```
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```
です。

**Comment by voluntas** [comment]
@anatawa12 ありがとうございます。ロジクール了解しました。調査してみます。

**Comment by anatawa12** [comment]
一緒に持っているPi3 model B V1.2(基盤いわく)では正しく起動できてました。OS情報は少々お待ちください

**Comment by voluntas** [comment]
@anatawa12 B と B+ で違いがある ... 感じなんでしょうか。OS 情報ありがとうございます。お待ちしてます。

**Comment by anatawa12** [comment]
Model Bの方のOSは8.0のようでした。
Model Bのリビジョン番号は`a22082`です。

```
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie
```

**Comment by tnoho** [comment]
> raspberry pi B+(リビジョン番号a020d3)

リビジョン番号から 3B+ だと理解してますが、相違ないでしょうか。B+ と 3B+ はかなり違うので。

**Comment by anatawa12** [comment]
ごめんなさい。 3 入れ忘れていました。

**Comment by tnoho** [comment]
ありがとうございます。調べてみます！

**Comment by anatawa12** [comment]
必要なこと、ものがあれば教えてください。すぐに用意しますので。

**Comment by voluntas** [comment]
@anatawa12 libasound2 は入っていますでしょうか？音声周りの問題と考えています。
また momo 起動時に --log-level=0 を指定して出力されるログを最大にして、その結果をこちらに貼っていただけると助かります。

**Comment by anatawa12** [comment]
libasound2に関してはこうなりました。
```
pi@raspberrypi:~ $ sudo apt-get install libasound2
Reading package lists... Done
Building dependency tree
Reading state information... Done
libasound2 is already the newest version (1.1.3-5+rpt4).
libasound2 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
```
ですので既にでにインストールされてました。
ログはこの様になりました。
[log.txt](https://github.com/shiguredo/momo/files/3269314/log.txt)

**Comment by tnoho** [comment]
通常ですと、このあとに再生デバイスの初期化処理が走るのですがそれが記録されていないので、asound の設定の問題かなと考えております。
`--no-sound` はマイクの音声を送らないオプションでして、再生デバイスは掴んでしまうのです。
再生デバイス周りの設定などログを見る限りでは特段触っているように見受けられないのですが、編集していたりしませんでしょうか。

**Comment by anatawa12** [comment]
編集した覚えはないですね。

**Comment by anatawa12** [comment]
リセットなどの方法はあるでしょうか？

**Comment by anatawa12** [comment]
今確認したところ、`libasound2`は `openjdk-8-jre`の前提としてインストールされてました。
それが関係しますか？

**Comment by tnoho** [comment]
そこは関係しないです。もう少し調べてみますので、少々お待ちください。

**Comment by tnoho** [comment]
[momo-raspbian_armv7-m75-issue74.tar.gz](https://github.com/shiguredo/momo/files/3269485/momo-raspbian_armv7-m75-issue74.tar.gz)

手元環境が M75 なので M75 になってしまっていますが、このバイナリを試していただけますか？ Audio を全て潰してあります。

**Comment by anatawa12** [comment]
通常に起動してhtml表示できました。
(Pi 3 Bの方と同じなのでバグではなく、ブラウザその他の問題だと勝手に思っている)映像がうまく流れないこと以外問題無いです。

**Comment by tnoho** [comment]
であれば、あたりですね。正式な対応方針は追って決めます。

映像がうまく流れないというバグは、それはそれで気になりますが。
Chrome で下記のコマンドで接続を試してみてダメそうなら

`./momo --log-level=1 --no-audio p2p`

全部のログを貼った Issue をまた、立てていただければと思います。
video-codec と video-bitrate オプションは P2P モードでは使えません。HTML で VP8 を指定してください。ビットレートはまた違う指定方法があるのですが、今の momo の html には記載していません。行いたい場合は `b=AS` でググるとヒットするかと思います。

**Comment by anatawa12** [comment]
#75 で話したとおり映像がうまく流れないことはこちらの原因でした。このissueでのクラッシュする問題は`uv4l`を終了させたあとでもクラッシュします

**Comment by voluntas** [comment]
@anatawa12 develop ブランチに libwebrtc M75 対応と、no-audio のときはデバイスを掴まないという仕組みを追加しています。リリースは先なので自前でビルドして動かしていただいても良いですか？

**Comment by anatawa12** [comment]
今確認したところ落ちましたね。ビルドをとりあえずやり直したりmac->piの転送の方法など変えて試します

**Comment by voluntas** [comment]
@anatawa12 確認した際のコマンドと、トレースログやログの出力などをお願いできますか？こちらでも確認させていただこうと思います。

**Comment by anatawa12** [comment]
momo自体は多分問題なかったです。僕が間違ってintel mac上で実行させようとしてしまったのか、ファイルを共有するときのミスかと思います

**Comment by anatawa12** [comment]
@voluntas 10日の時点でのdevelopブランチで問題なく実行できました。

**Comment by voluntas** [comment]
@anatawa12 無事動作したとのことで了解しました。このブランチは閉じさせていただきます。
