### ISSUE TITLE
macOS 版 Momo で VideoToolbox 利用時の解像度変更に対応する

### ISSUE THREAD

**Issue by voluntas** [shiguredo/momo#77]
macOS のハードウェアエンコーダ機能である VideoToolbox 利用時に回線が不安定になった際に解像度を下げる処理が入ったときに落ちるという問題を抱えています。

- https://developer.apple.com/documentation/videotoolbox

**Comment by tnoho** [comment]
配信開始直後の解像度を上げる処理で一発クラッシュなので、もうちょっと深刻ですｗ

**Comment by voluntas** [comment]
https://github.com/shiguredo/momo/pull/92 こちらにて解決しました。 @hakobera に感謝。
